"""esquema inicial

Revision ID: b7b107a6c7d8
Revises:
"""
from alembic import op
import sqlalchemy as sa

revision = 'b7b107a6c7d8'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avaliacao_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('vigente_desde', sa.Date(), nullable=False),
    sa.Column('vigente_ate', sa.Date(), nullable=True),
    sa.Column('perguntas', sa.JSON(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome', 'versao')
    )
    op.create_table('catalogos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo', sa.String(length=60), nullable=False),
    sa.Column('codigo', sa.String(length=60), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grupo', 'codigo')
    )
    with op.batch_alter_table('catalogos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalogos_grupo'), ['grupo'], unique=False)

    op.create_table('colaboradores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=180), nullable=False),
    sa.Column('telefone', sa.String(length=40), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('colaboradores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_colaboradores_nome'), ['nome'], unique=False)

    op.create_table('historico_processos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('codigo', sa.String(length=60), nullable=True),
    sa.Column('cliente', sa.String(length=180), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=True),
    sa.Column('referencia_arquivo', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historico_processos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historico_processos_ano'), ['ano'], unique=False)
        batch_op.create_index(batch_op.f('ix_historico_processos_cliente'), ['cliente'], unique=False)
        batch_op.create_index(batch_op.f('ix_historico_processos_codigo'), ['codigo'], unique=False)

    op.create_table('importacao_registros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lote', sa.String(length=36), nullable=False),
    sa.Column('arquivo', sa.Text(), nullable=False),
    sa.Column('aba', sa.String(length=160), nullable=True),
    sa.Column('linha', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('valor_bruto', sa.JSON(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('conflito', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('arquivo', 'aba', 'linha', 'checksum')
    )
    with op.batch_alter_table('importacao_registros', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_importacao_registros_checksum'), ['checksum'], unique=False)
        batch_op.create_index(batch_op.f('ix_importacao_registros_lote'), ['lote'], unique=False)

    op.create_table('locais',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('logradouro', sa.String(length=240), nullable=True),
    sa.Column('complemento', sa.String(length=120), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=60), nullable=True),
    sa.Column('pais', sa.String(length=60), nullable=False),
    sa.Column('cep', sa.String(length=20), nullable=True),
    sa.Column('instrucoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('locais', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locais_cidade'), ['cidade'], unique=False)

    op.create_table('organizacoes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=180), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizacoes_nome'), ['nome'], unique=False)

    op.create_table('papeis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.Column('permissoes', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('pessoas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=180), nullable=False),
    sa.Column('idioma', sa.String(length=30), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pessoas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pessoas_nome'), ['nome'], unique=False)

    op.create_table('regras_comissao',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('vigente_desde', sa.Date(), nullable=False),
    sa.Column('vigente_ate', sa.Date(), nullable=True),
    sa.Column('parametros', sa.JSON(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('versao')
    )
    op.create_table('contatos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.String(length=36), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('valor', sa.String(length=255), nullable=False),
    sa.Column('principal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contatos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contatos_pessoa_id'), ['pessoa_id'], unique=False)

    op.create_table('processos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('codigo', sa.String(length=60), nullable=False),
    sa.Column('cliente_id', sa.String(length=36), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('coordenador_id', sa.String(length=36), nullable=True),
    sa.Column('status_agenda', sa.String(length=30), nullable=False),
    sa.Column('status_operacao', sa.String(length=30), nullable=False),
    sa.Column('arquivado_em', sa.DateTime(), nullable=True),
    sa.Column('cancelado_em', sa.DateTime(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.CheckConstraint("tipo in ('exportacao','importacao','domestico','guarda_moveis')"),
    sa.ForeignKeyConstraint(['cliente_id'], ['pessoas.id'], ),
    sa.ForeignKeyConstraint(['coordenador_id'], ['colaboradores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processos_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processos_codigo'), ['codigo'], unique=True)
        batch_op.create_index(batch_op.f('ix_processos_coordenador_id'), ['coordenador_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processos_status_agenda'), ['status_agenda'], unique=False)
        batch_op.create_index(batch_op.f('ix_processos_status_operacao'), ['status_operacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_processos_tipo'), ['tipo'], unique=False)

    op.create_table('usuarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('papel_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['papel_id'], ['papeis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_papel_id'), ['papel_id'], unique=False)

    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entidade', sa.String(length=80), nullable=False),
    sa.Column('entidade_id', sa.String(length=36), nullable=False),
    sa.Column('campo', sa.String(length=80), nullable=True),
    sa.Column('valor_anterior', sa.Text(), nullable=True),
    sa.Column('valor_novo', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.String(length=36), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('origem', sa.String(length=30), nullable=False),
    sa.Column('operacao', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditoria_data'), ['data'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditoria_entidade'), ['entidade'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditoria_entidade_id'), ['entidade_id'], unique=False)

    op.create_table('avaliacoes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('processo_id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('respostas', sa.JSON(), nullable=False),
    sa.Column('respondida_em', sa.Date(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['processo_id'], ['processos.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['avaliacao_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('avaliacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_avaliacoes_processo_id'), ['processo_id'], unique=False)

    op.create_table('documentos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('processo_id', sa.String(length=36), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('categoria', sa.String(length=60), nullable=False),
    sa.Column('onedrive_id', sa.String(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('caminho_relativo', sa.Text(), nullable=True),
    sa.Column('data_documento', sa.Date(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['processo_id'], ['processos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documentos_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentos_processo_id'), ['processo_id'], unique=False)

    op.create_table('janelas_agenda',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('processo_id', sa.String(length=36), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.CheckConstraint('data_fim >= data_inicio'),
    sa.ForeignKeyConstraint(['processo_id'], ['processos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('janelas_agenda', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_janelas_agenda_processo_id'), ['processo_id'], unique=False)

    op.create_table('medidas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('processo_id', sa.String(length=36), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('unidade', sa.String(length=20), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['processo_id'], ['processos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medidas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medidas_processo_id'), ['processo_id'], unique=False)

    op.create_table('ordens_servico',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('processo_id', sa.String(length=36), nullable=False),
    sa.Column('numero', sa.String(length=80), nullable=True),
    sa.Column('emissor_id', sa.String(length=36), nullable=True),
    sa.Column('modalidade', sa.String(length=40), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['emissor_id'], ['organizacoes.id'], ),
    sa.ForeignKeyConstraint(['processo_id'], ['processos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ordens_servico_emissor_id'), ['emissor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ordens_servico_numero'), ['numero'], unique=False)
        batch_op.create_index(batch_op.f('ix_ordens_servico_processo_id'), ['processo_id'], unique=False)

    op.create_table('processo_local',
    sa.Column('processo_id', sa.String(length=36), nullable=False),
    sa.Column('local_id', sa.String(length=36), nullable=False),
    sa.Column('papel', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['local_id'], ['locais.id'], ),
    sa.ForeignKeyConstraint(['processo_id'], ['processos.id'], ),
    sa.PrimaryKeyConstraint('processo_id', 'local_id', 'papel')
    )
    op.create_table('processo_organizacao',
    sa.Column('processo_id', sa.String(length=36), nullable=False),
    sa.Column('organizacao_id', sa.String(length=36), nullable=False),
    sa.Column('papel', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacoes.id'], ),
    sa.ForeignKeyConstraint(['processo_id'], ['processos.id'], ),
    sa.PrimaryKeyConstraint('processo_id', 'organizacao_id', 'papel')
    )
    op.create_table('etapas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ordem_servico_id', sa.String(length=36), nullable=False),
    sa.Column('tipo', sa.String(length=60), nullable=False),
    sa.Column('sequencia', sa.Integer(), nullable=False),
    sa.Column('prevista_inicio', sa.Date(), nullable=True),
    sa.Column('prevista_fim', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('critica', sa.Boolean(), nullable=False),
    sa.Column('anotacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordens_servico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('etapas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_etapas_ordem_servico_id'), ['ordem_servico_id'], unique=False)
        batch_op.create_index('ix_etapas_prazo_status', ['prevista_fim', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_etapas_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_etapas_tipo'), ['tipo'], unique=False)

    op.create_table('movimentos_pool_comissoes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('processo_id', sa.String(length=36), nullable=True),
    sa.Column('avaliacao_id', sa.String(length=36), nullable=True),
    sa.Column('regra_id', sa.String(length=36), nullable=True),
    sa.Column('estorno_de_id', sa.String(length=36), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('justificativa', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('criado_por_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['avaliacao_id'], ['avaliacoes.id'], ),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['estorno_de_id'], ['movimentos_pool_comissoes.id'], ),
    sa.ForeignKeyConstraint(['processo_id'], ['processos.id'], ),
    sa.ForeignKeyConstraint(['regra_id'], ['regras_comissao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movimentos_pool_comissoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimentos_pool_comissoes_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimentos_pool_comissoes_processo_id'), ['processo_id'], unique=False)

    op.create_table('execucoes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('etapa_id', sa.String(length=36), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('local', sa.String(length=240), nullable=True),
    sa.Column('anotacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['etapa_id'], ['etapas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('execucoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execucoes_etapa_id'), ['etapa_id'], unique=False)

    op.create_table('execucao_colaborador',
    sa.Column('execucao_id', sa.String(length=36), nullable=False),
    sa.Column('colaborador_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaboradores.id'], ),
    sa.ForeignKeyConstraint(['execucao_id'], ['execucoes.id'], ),
    sa.PrimaryKeyConstraint('execucao_id', 'colaborador_id')
    )
    op.execute("""CREATE VIEW vw_processos_consolidados AS
        SELECT p.id, p.codigo, pe.nome AS cliente, p.tipo, p.status_agenda, p.status_operacao,
               p.coordenador_id, p.criado_em, p.arquivado_em, p.cancelado_em
        FROM processos p JOIN pessoas pe ON pe.id = p.cliente_id""")
    op.execute("""CREATE VIEW vw_agenda_futura AS
        SELECT p.id AS processo_id, p.codigo, pe.nome AS cliente, j.data_inicio, j.data_fim, j.tipo
        FROM processos p JOIN pessoas pe ON pe.id=p.cliente_id JOIN janelas_agenda j ON j.processo_id=p.id
        WHERE j.tipo='confirmada' AND j.data_fim >= CURRENT_DATE""")
    op.execute("""CREATE VIEW vw_pendencias_operacionais AS
        SELECT p.id AS processo_id, p.codigo, e.id AS etapa_id, e.tipo, e.prevista_fim, e.status,
               CASE WHEN e.prevista_fim < CURRENT_DATE THEN 'vencida' WHEN x.id IS NULL THEN 'sem_execucao' ELSE 'em_aberto' END AS pendencia
        FROM processos p JOIN ordens_servico os ON os.processo_id=p.id JOIN etapas e ON e.ordem_servico_id=os.id
        LEFT JOIN execucoes x ON x.etapa_id=e.id WHERE e.status <> 'concluida'""")
    op.execute("""CREATE VIEW vw_execucoes_equipes AS
        SELECT p.id AS processo_id, p.codigo, os.id AS ordem_servico_id, e.id AS etapa_id, x.id AS execucao_id,
               x.data_inicio, x.data_fim, x.local, c.id AS colaborador_id, c.nome AS colaborador
        FROM processos p JOIN ordens_servico os ON os.processo_id=p.id JOIN etapas e ON e.ordem_servico_id=os.id
        JOIN execucoes x ON x.etapa_id=e.id LEFT JOIN execucao_colaborador ec ON ec.execucao_id=x.id
        LEFT JOIN colaboradores c ON c.id=ec.colaborador_id""")
    op.execute("""CREATE VIEW vw_avaliacoes_consolidadas AS
        SELECT a.id, a.processo_id, p.codigo, t.nome AS template, t.versao, a.respondida_em, a.respostas
        FROM avaliacoes a JOIN processos p ON p.id=a.processo_id JOIN avaliacao_templates t ON t.id=a.template_id""")
    op.execute("""CREATE VIEW vw_movimentos_pool_comissoes AS
        SELECT m.id, m.processo_id, p.codigo, m.tipo, m.valor, m.estado, m.criado_em, m.regra_id, m.estorno_de_id
        FROM movimentos_pool_comissoes m LEFT JOIN processos p ON p.id=m.processo_id""")
    op.execute("""CREATE VIEW vw_qualidade_dados AS
        SELECT p.id AS processo_id, p.codigo,
          CASE WHEN NOT EXISTS (SELECT 1 FROM janelas_agenda j WHERE j.processo_id=p.id AND j.tipo='confirmada') THEN 1 ELSE 0 END AS sem_agenda_confirmada,
          CASE WHEN NOT EXISTS (SELECT 1 FROM medidas m WHERE m.processo_id=p.id AND m.tipo='estimado' AND m.unidade='m3') THEN 1 ELSE 0 END AS sem_estimativa_m3
        FROM processos p WHERE p.arquivado_em IS NULL AND p.cancelado_em IS NULL""")
    # ### end Alembic commands ###

def downgrade():
    for view in ('vw_qualidade_dados', 'vw_movimentos_pool_comissoes', 'vw_avaliacoes_consolidadas',
                 'vw_execucoes_equipes', 'vw_pendencias_operacionais', 'vw_agenda_futura',
                 'vw_processos_consolidados'):
        op.execute(sa.text(f"DROP VIEW IF EXISTS {view}"))
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('execucao_colaborador')
    with op.batch_alter_table('execucoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execucoes_etapa_id'))

    op.drop_table('execucoes')
    with op.batch_alter_table('movimentos_pool_comissoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimentos_pool_comissoes_processo_id'))
        batch_op.drop_index(batch_op.f('ix_movimentos_pool_comissoes_estado'))

    op.drop_table('movimentos_pool_comissoes')
    with op.batch_alter_table('etapas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_etapas_tipo'))
        batch_op.drop_index(batch_op.f('ix_etapas_status'))
        batch_op.drop_index('ix_etapas_prazo_status')
        batch_op.drop_index(batch_op.f('ix_etapas_ordem_servico_id'))

    op.drop_table('etapas')
    op.drop_table('processo_organizacao')
    op.drop_table('processo_local')
    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ordens_servico_processo_id'))
        batch_op.drop_index(batch_op.f('ix_ordens_servico_numero'))
        batch_op.drop_index(batch_op.f('ix_ordens_servico_emissor_id'))

    op.drop_table('ordens_servico')
    with op.batch_alter_table('medidas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medidas_processo_id'))

    op.drop_table('medidas')
    with op.batch_alter_table('janelas_agenda', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_janelas_agenda_processo_id'))

    op.drop_table('janelas_agenda')
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documentos_processo_id'))
        batch_op.drop_index(batch_op.f('ix_documentos_nome'))

    op.drop_table('documentos')
    with op.batch_alter_table('avaliacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_avaliacoes_processo_id'))

    op.drop_table('avaliacoes')
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditoria_entidade_id'))
        batch_op.drop_index(batch_op.f('ix_auditoria_entidade'))
        batch_op.drop_index(batch_op.f('ix_auditoria_data'))

    op.drop_table('auditoria')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_papel_id'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    with op.batch_alter_table('processos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processos_tipo'))
        batch_op.drop_index(batch_op.f('ix_processos_status_operacao'))
        batch_op.drop_index(batch_op.f('ix_processos_status_agenda'))
        batch_op.drop_index(batch_op.f('ix_processos_coordenador_id'))
        batch_op.drop_index(batch_op.f('ix_processos_codigo'))
        batch_op.drop_index(batch_op.f('ix_processos_cliente_id'))

    op.drop_table('processos')
    with op.batch_alter_table('contatos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contatos_pessoa_id'))

    op.drop_table('contatos')
    op.drop_table('regras_comissao')
    with op.batch_alter_table('pessoas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pessoas_nome'))

    op.drop_table('pessoas')
    op.drop_table('papeis')
    with op.batch_alter_table('organizacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizacoes_nome'))

    op.drop_table('organizacoes')
    with op.batch_alter_table('locais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locais_cidade'))

    op.drop_table('locais')
    with op.batch_alter_table('importacao_registros', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_importacao_registros_lote'))
        batch_op.drop_index(batch_op.f('ix_importacao_registros_checksum'))

    op.drop_table('importacao_registros')
    with op.batch_alter_table('historico_processos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historico_processos_codigo'))
        batch_op.drop_index(batch_op.f('ix_historico_processos_cliente'))
        batch_op.drop_index(batch_op.f('ix_historico_processos_ano'))

    op.drop_table('historico_processos')
    with op.batch_alter_table('colaboradores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_colaboradores_nome'))

    op.drop_table('colaboradores')
    with op.batch_alter_table('catalogos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalogos_grupo'))

    op.drop_table('catalogos')
    op.drop_table('avaliacao_templates')
    # ### end Alembic commands ###
